### ISSUE TITLE
Windows Server 2016/19 Not Working on Nfoservers

### ISSUE THREAD

**Issue by Wookiee-** [Yberion/JKA_YBEProxy#2]
I've tried this to run on windows server and it breaks/shutdown when a player connects.

**Comment by Yberion** [comment]
Did you build a "Release" version ? It doesn't work with a debug version.

Which version of Windows you're using ? Which SDK ?

**Comment by Wookiee-** [comment]
I've tried with release, it was windows server 2019 it doesn't matter now I moved to a linux server. I compiled it with Visual Studio 2019

**Comment by Wookiee-** [comment]
Update, it works on windows 10, just not on this windows server 2019 machine

**Comment by Yberion** [comment]
Ok thanks for the feedback, really strange, it's probably because of the ASM stuff.

Can't look at it, I'm busy atm.

**Comment by Wookiee-** [comment]
Edited the name of issue because it was misleading on what windows platform.
