### ISSUE TITLE
sv_fps 30 minimum cap, can't run at 20fps

### ISSUE THREAD

**Issue by kyle108** [Yberion/JKA_YBEProxy#3]
I've compiled YBEProxy in order to try it on a `linuxjampded` server running at `sv_fps` 20, but turned out YBEProxy caps sv_fps at minimum of 30 for some reason, without mentioning it.

When `sv_fps` is set to 20 or below, we can clearly tell that a server still runs at 30 FPS based on the following signs:

- Ping calculation is precise, which is not possible on `sv_fps 20`, where you should get rounded pings such as 48 for low pings etc. i.e if my current ping is 35, it will be 35 on `sv_fps 30`, but on `sv_fps 20` it will be approximately 48, which is normal due to impossibility of calculating precise ping on 20fps due to its natural limitations.
 
- When setting `sv_fps 5`, ping should double i.e. if my normal ping is 100 it should become 200, which doesn't happen because server continue operating at `sv_fps 30` internally and ping calculation is precise.
 
- Client-side snaps react to sv_fps change that makes a misleading impression of changed FPS, but it's only because JKA clients cap `/snaps` to the current /sv_fps. When I remove this autocap from my client (by rebuilding OpenJK), the sv_fps changes become unnoticeable even at `sv_fps 1` and server is playable, which is not normal.
 
 I didn't find any mentions of lower limit for sv_fps across your hackmd.io notes, but still would like to know if it's a known feature or something that you are unaware of and maybe a bug.

**Comment by Yberion** [comment]
Hello, there is no bug with `sv_fps 20` or the default value being `30`, it's still `20` by default and still all default behavior.

First of all, you're using `linuxjampded`, it should indeed display ping `48` with `sv_fps 20` with the default behavior. But the ping calculation and some other code that change the behavior of the ping, got hooked and "fixed", this way the ping calculation is more accurate no matter the `sv_fps` value.

When you set `sv_fps` to `5`, you shouldn't be able to see a difference when putting `/snaps` higher than 5.

The ping "fix" is in the patchnote `pingfix (sort of true ping) & fix ping calculation (c318f53 & 0301bea)`.
